### ISSUE TITLE
Websocket Connection Error

### ISSUE THREAD

**Issue by deepakmodidev** [HumeAI/hume-evi-next-js-starter#22]
<img width="534" height="530" alt="Image" src="https://github.com/user-attachments/assets/5a548346-52f0-4e7f-ae1f-231a2be6b791" />

Getting this erro on starting a call :
A websocket connection could not be established. Error message: WebSocket low-level error occurred (see browser/runtime console for native event details).

**Comment by ivaaan** [comment]
Hi @decodewithdeepak I'm looking into this, but in the meantime, can you please try another example: https://github.com/HumeAI/hume-api-examples/tree/main/evi/evi-next-js-pages-router-quickstart

It's very similar and I just confirmed it works OK!

**Comment by ivaaan** [comment]
UPD: fixed in #24, merging soon

**Comment by zachkrall** [comment]
Hi @decodewithdeepak,

Thanks again for surfacing this issue! It's been fixed in the main branch (#24). If you want to apply the changes to your own project locally, all you will need to do is update the Hume SDKs to the latest version.

```bash
# using pnpm (recommended)
pnpm install hume@latest @humeai/voice-react@latest

# with npm
npm install hume@latest @humeai/voice-react@latest
```

**Comment by deepakmodidev** [comment]
<img width="539" height="552" alt="Image" src="https://github.com/user-attachments/assets/f1dc1891-b178-454a-b9dd-26f719248463" />

<img width="686" height="73" alt="Image" src="https://github.com/user-attachments/assets/f3cd58d9-1eb6-4600-88b2-e440f04e2478" />

can you please try going to url => https://hume-evi-next-js-starter.vercel.app/
it's still not working; have you updated the vercel link also...
